name: Refresh Go Report Card

on:
  push:
    branches: [ main ]

jobs:
  goreportcard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run Go Report Card check
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          curl -X POST -F "repo=github.com/${GITHUB_REPOSITORY}" https://goreportcard.com/checks